# Generated by Django 5.0.1 on 2024-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
