# Generated by Django 5.0.1 on 2024-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_teacher_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
