# Generated by Django 5.0.1 on 2024-02-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='teacher',
        ),
    ]
