# Generated by Django 5.0.1 on 2024-02-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_user_teacher_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='user',
        ),
    ]
