# Generated by Django 5.0.1 on 2024-02-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_teacher_managers'),
        ('courses', '0004_alter_course_teacher_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher'),
        ),
    ]
