# Generated by Django 5.0.1 on 2024-02-17 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
