# Generated by Django 5.0.1 on 2024-03-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_profile_picture_url'),
        ('courses', '0008_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_courses', models.ManyToManyField(blank=True, related_name='cart_students', to='courses.course')),
                ('registered_courses', models.ManyToManyField(blank=True, related_name='registered_students', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
    ]
