# Generated by Django 5.0.1 on 2024-03-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_student_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_courses',
            old_name='user',
            new_name='student',
        ),
    ]
