# Generated by Django 5.0.1 on 2024-03-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_profile_picture_url'),
        ('courses', '0010_rename_user_student_courses_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_course_ids', models.ManyToManyField(blank=True, related_name='cart_students_ids', to='courses.course')),
                ('registered_course_ids', models.ManyToManyField(blank=True, related_name='registered_students_ids', to='courses.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_courses',
        ),
    ]
